### ISSUE TITLE
Rationale for variable-length public keys is off

### ISSUE THREAD

**Issue by davidben** [dstebila/draft-ietf-tls-hybrid-design#2]
(Filing this so we don't lose track of the other issue from the TLSWG thread.)

Section 3.2 defines a HybridKeyExchange structure with length prefixes and justifies it by saying:

> However we do add structure in the concatenation procedure, specifically including length fields, so that the concatenation operation is unambiguous. Note that among the Round 2 candidates in the NIST Post-Quantum Cryptography Standardization Project, not all algorithms have fixed public key sizes; for example, the SIKE key encapsulation mechanism permits compressed or uncompressed public keys at each security level, and the compressed and uncompressed formats are interoperable.

This justification, particularly the example, doesn't hold. While SIKE permits both compressed or uncompressed public keys, any TLS code point would need to pick one or the other (see [RFC8446](https://tools.ietf.org/html/rfc8446#section-4.2.8.2)).  Once the form is picked, I believe it is fixed-width.

Unlike #1, there isn't an immediate security flaw with variable-length public keys, but I also would consider it a sign of a poorly-specified primitive. We've seen elsewhere that such designs lead to interop issues (e.g. https://github.com/tlswg/tls13-spec/pull/458), as well as general implementation complexity. (Anecdotally, every time I review code that uses ECDSA, I find a mistake in handling the variable-length signature encoding.)

Additionally, one of the benefits of switching this design to the simpler separate codepoints model is to avoid a lowest common denominator problem. The specification could say to concatenate them, note that this requires fixed-length public keys (which is true in practice), and then mention in passing that if anyone does try to hybridize a variable-length algorithm, they can introduce length prefixes for just that code point. (And then in standardization we'll correct the flaw in the primitive, so no one ever needs to implement it! 😉)

**Comment by dstebila** [comment]
Thanks for copying that form the mailing list here.  Your argument seems reasonable to me.  Let me check with my coauthors for any further thoughts and I'll follow up here in a few days.
