### ISSUE TITLE
Explicitly assign and encode `shared_secret_1` and `shared_secret_2`

### ISSUE THREAD

**Issue by dconnolly** [dstebila/draft-ietf-tls-hybrid-design#28]
In the prose text, the order of the component shared secrets when calculating `concatenated_shared_secret` is described, but the items `shared_secret_1` and `shared_secret_2` are not defined, and ambiguous. It would be nice for implementers to explicitly assign them, hopefully per `NamedGroup` etc.

Also the serialization of the component schemes' shared secrets is not described or cited, it would be good to be explicit about how the shared secrets are turned into bytes before concatting them together. One can guess, but it would be safer to not need to guess.

**Comment by dstebila** [comment]
> In the prose text, the order of the component shared secrets when calculating `concatenated_shared_secret` is described, but the items `shared_secret_1` and `shared_secret_2` are not defined, and ambiguous. It would be nice for implementers to explicitly assign them, hopefully per `NamedGroup` etc.
> 
> Also the serialization of the component schemes' shared secrets is not described or cited, it would be good to be explicit about how the shared secrets are turned into bytes before concatting them together. One can guess, but it would be safer to not need to guess.

The idea was that each `NamedGroup` would define `shared_secret` including its serialization as bytes, and then we would just inherit those. Do you think that's problematic or unclear?

**Comment by dconnolly** [comment]
> > In the prose text, the order of the component shared secrets when calculating `concatenated_shared_secret` is described, but the items `shared_secret_1` and `shared_secret_2` are not defined, and ambiguous. It would be nice for implementers to explicitly assign them, hopefully per `NamedGroup` etc.
> > Also the serialization of the component schemes' shared secrets is not described or cited, it would be good to be explicit about how the shared secrets are turned into bytes before concatting them together. One can guess, but it would be safer to not need to guess.
> 
> The idea was that each `NamedGroup` would define `shared_secret` including its serialization as bytes, and then we would just inherit those. Do you think that's problematic or unclear?

It may be leaving a bit too much room too the documents that instantiate the new `NamedGroup`s to make it messy; maybe something like `shared_secret_1 = $first_component_algorithm` etc; I'll make a suggestion

**Comment by dstebila** [comment]
@dconnolly Was this resolved to your satisfaction by #29?

**Comment by dconnolly** [comment]
> @dconnolly Was this resolved to your satisfaction by #29?

Yes, this particular issue is basically resolved 👍
