### ISSUE TITLE
Consideration of alternative protocol arrangements?

### ISSUE THREAD

**Issue by ctz** [dstebila/draft-ietf-tls-hybrid-design#33]
Is there any prior discussion of  considered-but-rejected options in the design space which avoid the problems with this as it currently stands -- specifically, that using two hybrid groups for the same PQC algorithm lead to a bloated clienthello.

Apologies if this is retreading old ground; I didn't see any past mailing list traffic on this topic.

**Comment by thomwiggers** [comment]
There exists some discussion on some of this at least in older drafts of this document, e.g. https://datatracker.ietf.org/doc/html/draft-ietf-tls-hybrid-design-00#name-benefits-and-drawbacks-3

**Comment by ctz** [comment]
Thank you! I'll close this.
